/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Issue Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  NewOrg,
  NewOrgAdmin,
  OrgAdmin,
  OrgList,
  OrgPatch,
  OrgSummary
} from '../issueTrackerAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class PlatformService {
  private readonly http = inject(HttpClient);
/**
 * @summary List all organizations (platform owner)
 */
 getOrgs<TData = OrgList>( options?: HttpClientBodyOptions): Observable<TData>;
 getOrgs<TData = OrgList>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getOrgs<TData = OrgList>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getOrgs<TData = OrgList>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/platform/orgs`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/platform/orgs`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/platform/orgs`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Create an organization with its first admin
 */
 postOrg<TData = OrgSummary>(newOrg?: NewOrg, options?: HttpClientBodyOptions): Observable<TData>;
 postOrg<TData = OrgSummary>(newOrg?: NewOrg, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postOrg<TData = OrgSummary>(newOrg?: NewOrg, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postOrg<TData = OrgSummary>(
    newOrg?: NewOrg, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/platform/orgs`,
      newOrg,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/platform/orgs`,
      newOrg,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/platform/orgs`,
      newOrg,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Rename an organization or change its status
 */
 updateOrg<TData = OrgSummary>(id: string,
    orgPatch?: OrgPatch, options?: HttpClientBodyOptions): Observable<TData>;
 updateOrg<TData = OrgSummary>(id: string,
    orgPatch?: OrgPatch, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateOrg<TData = OrgSummary>(id: string,
    orgPatch?: OrgPatch, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateOrg<TData = OrgSummary>(
    id: string,
    orgPatch?: OrgPatch, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/platform/orgs/${id}`,
      orgPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/platform/orgs/${id}`,
      orgPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/platform/orgs/${id}`,
      orgPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Soft-delete an organization
 */
 deleteOrg<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteOrg<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteOrg<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteOrg<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/platform/orgs/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/platform/orgs/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/platform/orgs/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Add an admin to an organization
 */
 postOrgAdmin<TData = OrgAdmin>(id: string,
    newOrgAdmin?: NewOrgAdmin, options?: HttpClientBodyOptions): Observable<TData>;
 postOrgAdmin<TData = OrgAdmin>(id: string,
    newOrgAdmin?: NewOrgAdmin, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postOrgAdmin<TData = OrgAdmin>(id: string,
    newOrgAdmin?: NewOrgAdmin, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postOrgAdmin<TData = OrgAdmin>(
    id: string,
    newOrgAdmin?: NewOrgAdmin, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/platform/orgs/${id}/admins`,
      newOrgAdmin,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/platform/orgs/${id}/admins`,
      newOrgAdmin,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/platform/orgs/${id}/admins`,
      newOrgAdmin,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Remove an admin from an organization
 */
 deleteOrgAdmin<TData = void>(id: string,
    userId: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteOrgAdmin<TData = void>(id: string,
    userId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteOrgAdmin<TData = void>(id: string,
    userId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteOrgAdmin<TData = void>(
    id: string,
    userId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/platform/orgs/${id}/admins/${userId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/platform/orgs/${id}/admins/${userId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/platform/orgs/${id}/admins/${userId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

