/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Issue Tracker API
 * OpenAPI spec version: 0.1.0
 */
export type IssuePriority = typeof IssuePriority[keyof typeof IssuePriority];


export const IssuePriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  urgent: 'urgent',
} as const;

export type IssueCategory = typeof IssueCategory[keyof typeof IssueCategory];


export const IssueCategory = {
  bug: 'bug',
  feature_request: 'feature_request',
  ui_ux: 'ui_ux',
  performance: 'performance',
  billing: 'billing',
  other: 'other',
} as const;

export type IssueStatus = typeof IssueStatus[keyof typeof IssueStatus];


export const IssueStatus = {
  open: 'open',
  in_progress: 'in_progress',
  resolved: 'resolved',
  closed: 'closed',
} as const;

export interface Issue {
  id: number;
  orgId: string;
  createdBy: string;
  description: string;
  /** @nullable */
  assignedUser: string | null;
  /** @nullable */
  assignedUserName?: string | null;
  priority: IssuePriority;
  category: IssueCategory;
  status: IssueStatus;
  /** @nullable */
  screenshotPath: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  deletedAt: string | null;
}

export interface IssueList {
  issues: Issue[];
}

export interface Error {
  detail: string;
}

export interface NewIssue {
  /** @minLength 1 */
  description: string;
  assignedUser?: string;
  /** @minLength 1 */
  priority?: string;
  /** @minLength 1 */
  category?: string;
  screenshotPath?: string;
}

export interface IssuePatch {
  /** @minLength 1 */
  description?: string;
  /** @nullable */
  assignedUser?: string | null;
  /** @minLength 1 */
  priority?: string;
  /** @minLength 1 */
  category?: string;
  status?: IssueStatus;
  /** @nullable */
  screenshotPath?: string | null;
}

export interface Member {
  userId: string;
  email: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  imageUrl: string | null;
  role: string;
  permissions: string[];
  createdAt: string;
}

export interface MemberList {
  members: Member[];
}

export type Role = typeof Role[keyof typeof Role];


export const Role = {
  admin: 'admin',
  member: 'member',
  viewer: 'viewer',
} as const;

export interface NewMember {
  email: string;
  name?: string;
  role: Role;
  /** @minLength 8 */
  password: string;
}

export interface MemberPatch {
  name?: string;
  role?: Role;
}

export interface PasswordReset {
  /** @minLength 8 */
  password: string;
}

export type PriorityLabels = {[key: string]: string};

export interface Priority {
  id: number;
  orgId: string;
  key: string;
  label: string;
  labels: PriorityLabels;
  sortOrder: number;
}

export interface PriorityList {
  priorities: Priority[];
}

export type NewPriorityLabels = {[key: string]: string};

export interface NewPriority {
  /** @minLength 1 */
  key: string;
  /** @minLength 1 */
  label: string;
  labels?: NewPriorityLabels;
  sortOrder?: number;
}

export type PriorityPatchLabels = {[key: string]: string};

export interface PriorityPatch {
  /** @minLength 1 */
  key?: string;
  /** @minLength 1 */
  label?: string;
  labels?: PriorityPatchLabels;
  sortOrder?: number;
}

export type CategoryLabels = {[key: string]: string};

export interface Category {
  id: number;
  orgId: string;
  key: string;
  label: string;
  labels: CategoryLabels;
  sortOrder: number;
}

export interface CategoryList {
  categories: Category[];
}

export type NewCategoryLabels = {[key: string]: string};

export interface NewCategory {
  /** @minLength 1 */
  key: string;
  /** @minLength 1 */
  label: string;
  labels?: NewCategoryLabels;
  sortOrder?: number;
}

export type CategoryPatchLabels = {[key: string]: string};

export interface CategoryPatch {
  /** @minLength 1 */
  key?: string;
  /** @minLength 1 */
  label?: string;
  labels?: CategoryPatchLabels;
  sortOrder?: number;
}

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  enabled: boolean;
  sortOrder: number;
  createdAt: string;
}

export interface LanguageList {
  languages: Language[];
}

export interface NewLanguage {
  /** @minLength 2 */
  code: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  nativeName: string;
  sortOrder?: number;
  enabled?: boolean;
}

export interface LanguagePatch {
  /** @minLength 1 */
  name?: string;
  /** @minLength 1 */
  nativeName?: string;
  sortOrder?: number;
  enabled?: boolean;
}

export interface OrgAdmin {
  userId: string;
  email: string;
  /** @nullable */
  name: string | null;
}

export interface OrgSummary {
  id: string;
  name: string;
  status: string;
  createdAt: string;
  memberCount: number;
  admins: OrgAdmin[];
}

export interface OrgList {
  orgs: OrgSummary[];
}

export interface NewOrg {
  /** @minLength 1 */
  orgName: string;
  adminEmail: string;
  adminName?: string;
  /** @minLength 8 */
  adminPassword: string;
}

export type OrgPatchStatus = typeof OrgPatchStatus[keyof typeof OrgPatchStatus];


export const OrgPatchStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;

export interface OrgPatch {
  /** @minLength 1 */
  name?: string;
  status?: OrgPatchStatus;
}

export interface NewOrgAdmin {
  email: string;
  name?: string;
  /** @minLength 8 */
  password: string;
}

export interface MemberRole {
  permissions: string[];
  available: string[];
}

export interface MemberRolePatch {
  permissions: string[];
}

