/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Issue Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  Category,
  CategoryList,
  CategoryPatch,
  NewCategory
} from '../issueTrackerAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class CategoryService {
  private readonly http = inject(HttpClient);
/**
 * @summary List category options
 */
 getCategories<TData = CategoryList>( options?: HttpClientBodyOptions): Observable<TData>;
 getCategories<TData = CategoryList>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getCategories<TData = CategoryList>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getCategories<TData = CategoryList>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/categories`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/categories`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/categories`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Create a category option
 */
 postCategory<TData = Category>(newCategory?: NewCategory, options?: HttpClientBodyOptions): Observable<TData>;
 postCategory<TData = Category>(newCategory?: NewCategory, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postCategory<TData = Category>(newCategory?: NewCategory, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postCategory<TData = Category>(
    newCategory?: NewCategory, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/categories`,
      newCategory,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/categories`,
      newCategory,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/categories`,
      newCategory,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Update a category option
 */
 updateCategory<TData = Category>(id: number,
    categoryPatch?: CategoryPatch, options?: HttpClientBodyOptions): Observable<TData>;
 updateCategory<TData = Category>(id: number,
    categoryPatch?: CategoryPatch, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateCategory<TData = Category>(id: number,
    categoryPatch?: CategoryPatch, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateCategory<TData = Category>(
    id: number,
    categoryPatch?: CategoryPatch, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/categories/${id}`,
      categoryPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/categories/${id}`,
      categoryPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/categories/${id}`,
      categoryPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Delete a category option
 */
 deleteCategory<TData = void>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteCategory<TData = void>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteCategory<TData = void>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteCategory<TData = void>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/categories/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/categories/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/categories/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

