/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Issue Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  Member,
  MemberList,
  MemberPatch,
  NewMember,
  PasswordReset
} from '../issueTrackerAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class MemberService {
  private readonly http = inject(HttpClient);
/**
 * @summary List org members
 */
 getMembers<TData = MemberList>( options?: HttpClientBodyOptions): Observable<TData>;
 getMembers<TData = MemberList>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getMembers<TData = MemberList>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getMembers<TData = MemberList>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/members`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/members`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/members`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Create a member
 */
 postMember<TData = Member>(newMember?: NewMember, options?: HttpClientBodyOptions): Observable<TData>;
 postMember<TData = Member>(newMember?: NewMember, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postMember<TData = Member>(newMember?: NewMember, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postMember<TData = Member>(
    newMember?: NewMember, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/members`,
      newMember,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/members`,
      newMember,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/members`,
      newMember,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Update a member
 */
 updateMember<TData = Member>(userId: string,
    memberPatch?: MemberPatch, options?: HttpClientBodyOptions): Observable<TData>;
 updateMember<TData = Member>(userId: string,
    memberPatch?: MemberPatch, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateMember<TData = Member>(userId: string,
    memberPatch?: MemberPatch, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateMember<TData = Member>(
    userId: string,
    memberPatch?: MemberPatch, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/members/${userId}`,
      memberPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/members/${userId}`,
      memberPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/members/${userId}`,
      memberPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Remove a member
 */
 deleteMember<TData = void>(userId: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteMember<TData = void>(userId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteMember<TData = void>(userId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteMember<TData = void>(
    userId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/members/${userId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/members/${userId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/members/${userId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Reset a member's password
 */
 resetMemberPassword<TData = void>(userId: string,
    passwordReset?: PasswordReset, options?: HttpClientBodyOptions): Observable<TData>;
 resetMemberPassword<TData = void>(userId: string,
    passwordReset?: PasswordReset, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 resetMemberPassword<TData = void>(userId: string,
    passwordReset?: PasswordReset, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  resetMemberPassword<TData = void>(
    userId: string,
    passwordReset?: PasswordReset, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/members/${userId}/password`,
      passwordReset,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/members/${userId}/password`,
      passwordReset,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/members/${userId}/password`,
      passwordReset,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

