/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Issue Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  MemberRole,
  MemberRolePatch
} from '../issueTrackerAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class RoleService {
  private readonly http = inject(HttpClient);
/**
 * @summary The member role's permissions + the grantable set
 */
 getMemberRole<TData = MemberRole>( options?: HttpClientBodyOptions): Observable<TData>;
 getMemberRole<TData = MemberRole>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getMemberRole<TData = MemberRole>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getMemberRole<TData = MemberRole>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/roles/member`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/roles/member`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/roles/member`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Update the member role's permissions (admin)
 */
 updateMemberRole<TData = MemberRole>(memberRolePatch?: MemberRolePatch, options?: HttpClientBodyOptions): Observable<TData>;
 updateMemberRole<TData = MemberRole>(memberRolePatch?: MemberRolePatch, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateMemberRole<TData = MemberRole>(memberRolePatch?: MemberRolePatch, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateMemberRole<TData = MemberRole>(
    memberRolePatch?: MemberRolePatch, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/roles/member`,
      memberRolePatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/roles/member`,
      memberRolePatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/roles/member`,
      memberRolePatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

