/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Issue Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  NewPriority,
  Priority,
  PriorityList,
  PriorityPatch
} from '../issueTrackerAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class PriorityService {
  private readonly http = inject(HttpClient);
/**
 * @summary List priority options
 */
 getPriorities<TData = PriorityList>( options?: HttpClientBodyOptions): Observable<TData>;
 getPriorities<TData = PriorityList>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getPriorities<TData = PriorityList>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getPriorities<TData = PriorityList>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/priorities`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/priorities`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/priorities`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Create a priority option
 */
 postPriority<TData = Priority>(newPriority?: NewPriority, options?: HttpClientBodyOptions): Observable<TData>;
 postPriority<TData = Priority>(newPriority?: NewPriority, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postPriority<TData = Priority>(newPriority?: NewPriority, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postPriority<TData = Priority>(
    newPriority?: NewPriority, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/priorities`,
      newPriority,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/priorities`,
      newPriority,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/priorities`,
      newPriority,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Update a priority option
 */
 updatePriority<TData = Priority>(id: number,
    priorityPatch?: PriorityPatch, options?: HttpClientBodyOptions): Observable<TData>;
 updatePriority<TData = Priority>(id: number,
    priorityPatch?: PriorityPatch, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updatePriority<TData = Priority>(id: number,
    priorityPatch?: PriorityPatch, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updatePriority<TData = Priority>(
    id: number,
    priorityPatch?: PriorityPatch, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/priorities/${id}`,
      priorityPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/priorities/${id}`,
      priorityPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/priorities/${id}`,
      priorityPatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Delete a priority option
 */
 deletePriority<TData = void>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 deletePriority<TData = void>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deletePriority<TData = void>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deletePriority<TData = void>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/priorities/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/priorities/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/priorities/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

