/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Issue Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  Language,
  LanguageList,
  LanguagePatch,
  NewLanguage
} from '../issueTrackerAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly http = inject(HttpClient);
/**
 * @summary List the org's enabled UI languages
 */
 getLanguages<TData = LanguageList>( options?: HttpClientBodyOptions): Observable<TData>;
 getLanguages<TData = LanguageList>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getLanguages<TData = LanguageList>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getLanguages<TData = LanguageList>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/languages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/languages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/languages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Add a language to the org (admin)
 */
 postLanguage<TData = Language>(newLanguage?: NewLanguage, options?: HttpClientBodyOptions): Observable<TData>;
 postLanguage<TData = Language>(newLanguage?: NewLanguage, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postLanguage<TData = Language>(newLanguage?: NewLanguage, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postLanguage<TData = Language>(
    newLanguage?: NewLanguage, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/languages`,
      newLanguage,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/languages`,
      newLanguage,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/languages`,
      newLanguage,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary List all of the org's languages (admin)
 */
 getAllLanguages<TData = LanguageList>( options?: HttpClientBodyOptions): Observable<TData>;
 getAllLanguages<TData = LanguageList>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getAllLanguages<TData = LanguageList>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getAllLanguages<TData = LanguageList>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/languages/all`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/languages/all`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/languages/all`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Edit a language (admin)
 */
 updateLanguage<TData = Language>(code: string,
    languagePatch?: LanguagePatch, options?: HttpClientBodyOptions): Observable<TData>;
 updateLanguage<TData = Language>(code: string,
    languagePatch?: LanguagePatch, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateLanguage<TData = Language>(code: string,
    languagePatch?: LanguagePatch, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateLanguage<TData = Language>(
    code: string,
    languagePatch?: LanguagePatch, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/languages/${code}`,
      languagePatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/languages/${code}`,
      languagePatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/languages/${code}`,
      languagePatch,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Remove a language from the org (admin)
 */
 deleteLanguage<TData = void>(code: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteLanguage<TData = void>(code: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteLanguage<TData = void>(code: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteLanguage<TData = void>(
    code: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/languages/${code}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/languages/${code}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/languages/${code}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

